/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.neighbor.vstream;

public class VStreamManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VStreamManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VStreamManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        vstreamJNI.delete_VStreamManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VStreamManager() {
    this(vstreamJNI.new_VStreamManager(), true);
  }

  public int initSession(String identify, String serverIp, int serverPort) {
    return vstreamJNI.VStreamManager_initSession(swigCPtr, this, identify, serverIp, serverPort);
  }

  public void destroySession() {
    vstreamJNI.VStreamManager_destroySession(swigCPtr, this);
  }

  public boolean isConnected() {
    return vstreamJNI.VStreamManager_isConnected(swigCPtr, this);
  }

  public int sendAudioData(int sampleRate, int channel, java.math.BigInteger pts, byte[] payload, int payloadSize) {
    return vstreamJNI.VStreamManager_sendAudioData(swigCPtr, this, sampleRate, channel, pts, payload, payloadSize);
  }

  public int sendVideoData(boolean isIFrame, int fps, int resolution, java.math.BigInteger pts, byte[] payload, int payloadSize) {
    return vstreamJNI.VStreamManager_sendVideoData(swigCPtr, this, isIFrame, fps, resolution, pts, payload, payloadSize);
  }

}
